import type { Metadata } from "next";
import { Poppins, Jost, Bebas_Neue } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar'

const poppins = Poppins({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100','200', '300', '400', '500', '600', '700', '800', '900']
 });

const jost = Jost({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-jost',
})

const bebas_neue = Bebas_Neue({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bebas_neue',
  weight:['400']
})


export const metadata: Metadata = {
  title: "CoderXme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${jost.variable} ${bebas_neue.variable}`}>
        <Navbar />
         {children}
        </body>
    </html>
  );
}
